[build]
  command = "cd web && npm ci --prefer-offline --no-audit && npm run build"
  publish = "web/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline --no-audit"
  NPM_CONFIG_PRODUCTION = "false"

[[redirects]]
  from = "/api/*"
  to = "https://chat-app-twilight-snow-4634.fly.dev/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  included_files = ["supabase/**"]

[functions."chat"]
  included_files = ["supabase/**"]

[functions."mcp"]
  included_files = ["supabase/**"]

[functions."crm_upsert_lead"]
  included_files = ["supabase/**"]

[functions."calendar_block_tentative"]
  included_files = ["supabase/**"]

[functions."crawler_fetch_listings"]
  included_files = ["supabase/**"]

[functions."voice_connect_call"]
  included_files = ["supabase/**"] 